feat: add phone authentication by otp, added translations
azawert/comp_club pull request #9
Opened 2023-11-04 13:07 UTC by azawert

2023-11-04 13:09 UTC, azawert commented on vite.config.ts
судя по всему для того, чтобы при локальной разработке получать смс коды - необходимо добавить свой урл в whitelist firebase, из-за этого пришлось переделать на локалхост, т.к обычный vite урл не хотел вписываться в этот whitelist

2023-11-04 21:08 UTC, remadyt requested changes

2023-11-04 21:08 UTC, remadyt commented on src/features/auth-by-phone/ui/components/otp-form.tsx
> +    if (value.length === 6) {
do not use magic number, here and all such places

2023-11-04 21:08 UTC, remadyt commented on src/features/auth-by-phone/ui/components/otp-form.tsx
> +          onChange={(value) => handleInputChange(value)}
why need (value) => (value) here? ```onChange={ handleInputChange}``` not working?

2023-11-04 21:08 UTC, remadyt commented on src/features/auth-by-phone/ui/components/otp-form.tsx
> +            onClick={() => dispatch(sendSmsCode(form.values.phone))}
create form, and use submit

2023-11-04 21:08 UTC, remadyt commented on src/features/auth-by-phone/ui/components/phone-form.tsx
> +  const phoneNumber = form.values.phone.slice(1, form.values.phone.length)
create helper for number formatting

2023-11-04 21:08 UTC, remadyt commented on src/features/auth-by-phone/ui/components/phone-form.tsx
> +          disabled={phoneNumber.length < 11}
create const for this

2023-11-04 21:08 UTC, remadyt commented on src/features/auth-by-phone/ui/components/phone-form.tsx
> +          onClick={() => dispatch(sendSmsCode(form.values.phone))}
same, need create func for this

2023-11-04 21:08 UTC, remadyt commented on src/features/auth-by-phone/ui/form-with-phone-and-otp.tsx
> +        value.match('[0-9]{11}') ? undefined : t('auth.enterPhoneNumber'),
use yup instead of this

2023-11-04 21:08 UTC, remadyt commented on src/features/auth-by-phone/ui/form-with-phone-and-otp.tsx
> +    initialValues: {
move INITIAL_VALUES to config

2023-11-04 21:08 UTC, remadyt commented on src/features/auth-by-phone/ui/form-with-phone-and-otp.tsx
> +      <Flex align={'center'} justify={'center'}>
add prettier rule, if you using string ```{}``` not needed

2023-11-04 21:08 UTC, remadyt commented on src/main.tsx
> +  <React.StrictMode>
remove strict mode

2023-11-04 21:08 UTC, remadyt commented on src/pages/auth/model/services/verification-by-phone.ts
> +      console.log(res)
why u need console here?

2023-11-04 21:08 UTC, remadyt commented on src/pages/auth/model/services/verification-by-phone.ts
> +      form.reset()
what form will be reset? i think need add form name

2023-11-04 21:08 UTC, remadyt commented on src/pages/auth/model/slice/auth-slice.ts
> +      state.isError = false
boolean error its bad, you need to display the text error that comes

2023-11-04 21:08 UTC, remadyt commented on src/features/auth-by-phone/const/auth-step.tsx
> +  selectedStep: EAuthStep
rename to currentStep

2023-11-04 21:08 UTC, remadyt commented on src/features/auth-by-phone/const/auth-step.tsx
> +export const AuthStep: FC<IProps> = ({ selectedStep, ...rest }) => {
remove this and use only ```const Component = STEP_AUTH_MAPPER[selectedStep]``` in auth page

2023-11-04 21:08 UTC, remadyt commented on src/features/auth-by-phone/model/types/types.ts
> +export interface IForm {
IAuthForm

2023-11-04 21:08 UTC, remadyt commented on src/features/auth-by-phone/types/types.ts
> +import { IForm } from '..'
i think its bad path

2023-11-04 21:08 UTC, remadyt commented on src/features/auth-by-phone/ui/components/otp-form.tsx
> +    useState<number>(() => 60)
try to use https://mantine.dev/hooks/use-interval/ here

2023-11-06 09:12 UTC, remadyt requested changes

2023-11-06 09:12 UTC, remadyt commented on src/app/provider/route-provider/ui/app-router.tsx
> +        {Object.values(routeConfig).map(({ element, path }) => (
try implement this without ```Object.values```

2023-11-06 09:12 UTC, remadyt commented on src/app/provider/route-provider/ui/app-router.tsx
> +    <Suspense fallback="Loading">
use Loader from Mantine

2023-11-06 09:12 UTC, remadyt commented on src/app/provider/store/config/store.ts
> +console.log(createReduxToolkitStore().getState())
why need this console?

2023-11-06 09:12 UTC, remadyt commented on src/features/auth-by-phone/ui/components/otp-form.tsx
> +    if (seconds === 0) {
move to const

2023-11-06 09:12 UTC, remadyt commented on src/features/auth-by-phone/ui/components/otp-form.tsx
> +            onChange={(value) => handleInputChange(value)}
```onChange={handleInputChange}```

2023-11-06 09:12 UTC, remadyt commented on src/features/auth-by-phone/ui/components/otp-form.tsx
> +              disabled={seconds !== 0}
move to const

2023-11-06 09:12 UTC, remadyt commented on src/features/auth-by-phone/ui/components/phone-form.tsx
> +  const dispatch = useAppDispatch()
saperate hooks, constants by empty line here and all such places

2023-11-06 09:12 UTC, remadyt commented on src/features/auth-by-phone/ui/components/phone-form.tsx
> +          {form.errors.phone && (
error by default do not shown?

2023-11-06 09:12 UTC, remadyt commented on src/features/auth-by-phone/ui/components/phone-form.tsx
> +          {t('Продолжить с Google')}
auth.google, fix here and all such places

2023-11-06 09:12 UTC, remadyt commented on src/pages/auth/model/const/validation-schema.ts
> +  phone: Yup.string().min(11, 'Введите корректный номер телефона'),
add translations

2023-11-06 09:12 UTC, remadyt commented on src/pages/auth/model/services/verification-by-phone.ts
use camelCase in naming here and all such places

2023-11-06 09:12 UTC, remadyt commented on src/pages/auth/model/services/verification-by-phone.ts
> +      return rejectWithValue('Произошла ошибка')
try without return, reject with value does it under the hood. And you need to display the error from firebase

2023-11-06 09:12 UTC, remadyt commented on src/pages/auth/model/services/verification-by-phone.ts
> +    return rejectWithValue('Произошла ошибка')
same

2023-11-06 09:12 UTC, remadyt commented on src/pages/auth/model/slice/auth-slice.ts
> +  error: undefined,
try to refactor, undefined its crutch

2023-11-06 09:12 UTC, remadyt commented on src/pages/auth/model/types/types.ts
> +  error: string | undefined
try to fix

2023-11-06 09:12 UTC, remadyt commented on src/pages/auth/ui/auth-page.tsx
> +  const { selectedStep } = useSelector((state: IStateSchema) => state.auth)
separate by empty line

2023-11-06 09:12 UTC, remadyt commented on src/pages/auth/ui/auth-page.tsx
> +            <Text size="xl">{t('Войдите')}</Text>
fix

2023-11-06 09:12 UTC, remadyt commented on src/shared/config/route/route-config.tsx
> +export enum AppRoutes {
create const instead of enum

2023-11-06 09:12 UTC, remadyt commented on src/shared/config/route/route-config.tsx
> +  [AppRoutes.MAIN]: {
mapper not needed here, use const AppRoutes.Main

2023-11-06 09:12 UTC, remadyt commented on src/shared/helpers/firebase-helpers.ts
> +    return null
why null?

2023-11-06 09:12 UTC, remadyt commented on src/shared/helpers/firebase-helpers.ts
> +    const querySnapshot = await getDocs(q)
create helper for all datebase functions

look this tamlpate
<img width="738" alt="image" src="https://github.com/azawert/comp_club/assets/74316916/12dbde34-9277-459c-a167-5577ad612273">

2023-11-06 09:14 UTC, remadyt requested changes

2023-11-06 09:14 UTC, remadyt commented on src/app/provider/store/ui/store-provider.tsx
> +export const StoreProvider: FC<{ children: ReactNode }> = ({ children }) => {
why u not use PropsWithChildren?

2023-11-06 09:14 UTC, remadyt commented on src/features/auth-by-phone/ui/components/otp-form.tsx
> +            length={6}
move to const

2023-11-06 09:14 UTC, remadyt commented on src/features/auth-by-phone/ui/components/phone-form.tsx
> +        <Flex direction={'column'}>
why u not add rule to prettier? ```{}``` not needed if u path ```string param```

2023-11-06 19:57 UTC, azawert commented on src/features/auth-by-phone/ui/components/phone-form.tsx
> +          {form.errors.phone && (
yep

2023-11-07 16:49 UTC, remadyt requested changes

2023-11-07 16:49 UTC, remadyt commented on src/features/auth-by-phone/ui/components/otp-form.tsx
> +    // eslint-disable-next-line react-hooks/exhaustive-deps
fix eslint error

2023-11-07 16:49 UTC, remadyt commented on src/features/auth-by-phone/ui/components/phone-form.tsx
> +          onClick={handleSendSmsClick}
handleSendSms

2023-11-07 16:49 UTC, remadyt commented on src/pages/auth/model/services/verification-by-phone.ts
> +    } catch (e: any) {
fix any

2023-11-07 16:49 UTC, remadyt commented on src/pages/auth/model/services/verification-by-phone.ts
> +        rejectWithValue(e.message)
refactor

2023-11-07 16:49 UTC, remadyt commented on src/pages/auth/model/services/verification-by-phone.ts
> +    extra.navigate?.('/')
use Paths.Main

2023-11-07 18:49 UTC, merged